import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AboutCard from "@/components/rightProfile/AboutCard";
import RightProfileCard from "@/components/rightProfile/RightProfileCard";
import CurrentRoles from "@/components/rightProfile/CurrentRoles";
import AchievementsCard from "@/components/rightProfile/AchievementsCard";
import VisionCard from "@/components/rightProfile/VisionCard";
import SocialMediaCard from "@/components/rightProfile/SocialMediaCard";
import ContactCard from "@/components/rightProfile/ContactCard";
import PopularTags from "@/components/rightProfile/PopularTags";
import Categories from "@/components/rightProfile/Categories";
import NewsletterSignup from "@/components/rightProfile/NewsletterSignup";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* MAIN FLEX WRAPPER */}
        <div className="flex">

          {/* LEFT CONTENT (scrolls normally) */}
          <div className="w-full mx-auto ml-[179px] pr-5">
            {children}
          </div>

          {/* RIGHT SIDEBAR (fixed to the screen + scrollable) */}
          <div
            className="fixed right-0 top-0 h-screen  overflow-x-auto 
               border-l border-gray-200 bg-white 
               w-[380px] p-5"
          >
            <RightProfileCard />
            <AboutCard />
            <CurrentRoles />
            <AchievementsCard />
            <VisionCard />
            <SocialMediaCard />
            <ContactCard />
            <Categories />
            <PopularTags />
            <NewsletterSignup />
          </div>

        </div>

      </body>
    </html>
  );
}
